# Site settings
title: Quatroka | Blog
email: monteiro.leonardosantos@gmail.com
description: >
  Quatroka's Blog. Statistics, projects and postings on various subjects. - By: Leonardo S. Monteiro
baseurl: ""
url: "https://quatroka.github.io" # the base hostname & protocol for your site
facebook_username: quatroka
twitter_username: quatroka
medium_username: quatroka
github_username:  quatroka
linkedin_username: quatroka

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
